### ISSUE TITLE
Does not build.

### ISSUE THREAD

**Issue by sheki** [twitter-archive/scala-zookeeper-client#3] opened 2011-09-20 15:36 UTC
Does not build currently with Scala 2.9.1 and the dependency on configgy is broken.

**Comment by ryanking** [comment] 2011-10-10 23:59
This should be fixed now. If not, please show me the error you're seeing.

**Closed as completed by ryanking** 2011-10-10 23:59 UTC

**Comment by kevinclark** [comment] 2011-10-22 11:47
I'm not getting a successful build either, though I do off of @krasserm's tree:

```
[scala-zookeeper-client (master)] ➔ sbt 
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (9911kB/588ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.4 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    15 artifacts copied, 0 already retrieved (4096kB/327ms)
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] 
[info] Updating plugins...
[warn]  module not found: org.markdownj#markdownj;0.3.0-1.0.2b4
[warn] ==== local: tried
[warn]   /Users/kevinc/.ivy2/local/org.markdownj/markdownj/0.3.0-1.0.2b4/ivys/ivy.xml
[warn]   -- artifact org.markdownj#markdownj;0.3.0-1.0.2b4!markdownj.jar:
[warn]   /Users/kevinc/.ivy2/local/org.markdownj/markdownj/0.3.0-1.0.2b4/jars/markdownj.jar
[warn] ==== twitter.com: tried
[warn]   http://maven.twttr.com/org/markdownj/markdownj/0.3.0-1.0.2b4/markdownj-0.3.0-1.0.2b4.pom
[warn]   -- artifact org.markdownj#markdownj;0.3.0-1.0.2b4!markdownj.jar:
[warn]   http://maven.twttr.com/org/markdownj/markdownj/0.3.0-1.0.2b4/markdownj-0.3.0-1.0.2b4.jar
[warn]  module not found: org.freemarker#freemarker;2.3.16
[warn] ==== local: tried
[warn]   /Users/kevinc/.ivy2/local/org.freemarker/freemarker/2.3.16/ivys/ivy.xml
[warn]   -- artifact org.freemarker#freemarker;2.3.16!freemarker.jar:
[warn]   /Users/kevinc/.ivy2/local/org.freemarker/freemarker/2.3.16/jars/freemarker.jar
[warn] ==== twitter.com: tried
[warn]   http://maven.twttr.com/org/freemarker/freemarker/2.3.16/freemarker-2.3.16.pom
[warn]   -- artifact org.freemarker#freemarker;2.3.16!freemarker.jar:
[warn]   http://maven.twttr.com/org/freemarker/freemarker/2.3.16/freemarker-2.3.16.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.markdownj#markdownj;0.3.0-1.0.2b4: not found
[warn]  :: org.freemarker#freemarker;2.3.16: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[warn] :: problems summary ::
[warn] :::: WARNINGS
[warn]      module not found: org.markdownj#markdownj;0.3.0-1.0.2b4
[warn]  ==== local: tried
[warn]    /Users/kevinc/.ivy2/local/org.markdownj/markdownj/0.3.0-1.0.2b4/ivys/ivy.xml
[warn]    -- artifact org.markdownj#markdownj;0.3.0-1.0.2b4!markdownj.jar:
[warn]    /Users/kevinc/.ivy2/local/org.markdownj/markdownj/0.3.0-1.0.2b4/jars/markdownj.jar
[warn]  ==== twitter.com: tried
[warn]    http://maven.twttr.com/org/markdownj/markdownj/0.3.0-1.0.2b4/markdownj-0.3.0-1.0.2b4.pom
[warn]    -- artifact org.markdownj#markdownj;0.3.0-1.0.2b4!markdownj.jar:
[warn]    http://maven.twttr.com/org/markdownj/markdownj/0.3.0-1.0.2b4/markdownj-0.3.0-1.0.2b4.jar
[warn]      module not found: org.freemarker#freemarker;2.3.16
[warn]  ==== local: tried
[warn]    /Users/kevinc/.ivy2/local/org.freemarker/freemarker/2.3.16/ivys/ivy.xml
[warn]    -- artifact org.freemarker#freemarker;2.3.16!freemarker.jar:
[warn]    /Users/kevinc/.ivy2/local/org.freemarker/freemarker/2.3.16/jars/freemarker.jar
[warn]  ==== twitter.com: tried
[warn]    http://maven.twttr.com/org/freemarker/freemarker/2.3.16/freemarker-2.3.16.pom
[warn]    -- artifact org.freemarker#freemarker;2.3.16!freemarker.jar:
[warn]    http://maven.twttr.com/org/freemarker/freemarker/2.3.16/freemarker-2.3.16.jar
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: org.markdownj#markdownj;0.3.0-1.0.2b4: not found
[warn]      :: org.freemarker#freemarker;2.3.16: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[info] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] sbt.ResolveException: unresolved dependency: org.markdownj#markdownj;0.3.0-1.0.2b4: not found
[error] unresolved dependency: org.freemarker#freemarker;2.3.16: not found
sbt.ResolveException: unresolved dependency: org.markdownj#markdownj;0.3.0-1.0.2b4: not found
unresolved dependency: org.freemarker#freemarker;2.3.16: not found

 Hit enter to retry or 'exit' to quit: 
```

**Comment by krasserm** [comment] 2011-10-22 16:19
Kevin, I just built https://github.com/krasserm/scala-zookeeper-client but cannot reproduce the errors you reported. Can you please try again with a clean Ivy cache? Btw, the build settings in my fork significantly differ from those here (mine are based on 2.0.0, several deps were excluded, but Scala 2.9.1 is used).

**Comment by kevinclark** [comment] 2011-10-22 21:08
@krasserm Sorry, I phrased that awkwardly. Your branch builds fine. @twitter's doesn't. The errors are from this repo.

**Comment by ryanking** [comment] 2011-10-28 22:30
I think the dependency issues are all fixed now. Scala 2.9 isn't going to be supported by any twitter libraries for awhile (because it breaks a bunch of java integration, which is a big deal for us)
